# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TGMailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.PositiveIntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com'), (3, 'facebook.com')])),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(-1, 'Failed'), (0, 'Draft'), (5, 'In progress'), (8, 'Partially completed'), (10, 'Completed')], default=0)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(default='Empty')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sent',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TGMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.PositiveIntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com'), (3, 'facebook.com')])),
                ('created', models.DateTimeField(auto_now=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgconnector.TGMailing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TGSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.PositiveIntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com'), (3, 'facebook.com')])),
                ('created', models.DateTimeField(auto_now=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgconnector.TGMailing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.PositiveIntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com'), (3, 'facebook.com')])),
                ('created', models.DateTimeField(auto_now=True)),
                ('sid', models.PositiveIntegerField()),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Unsubscribed'), (-1, 'Inactive')], default=-1)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_contact', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_self', models.BooleanField(default=False)),
                ('is_mutual_contact', models.BooleanField(default=False)),
                ('is_restricted', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tgsegment',
            name='users',
            field=models.ManyToManyField(to='tgconnector.TGUser'),
        ),
        migrations.AddField(
            model_name='tgmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgconnector.TGUser'),
        ),
        migrations.AddField(
            model_name='tgmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
