# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgconnector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmessage',
            name='sid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
