# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgconnector', '0003_tgmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmailing',
            name='read_state_update',
            field=models.IntegerField(choices=[(1, 'Updating is required'), (2, 'Updating state is completed')], default=2),
        ),
    ]
