# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerChainItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_start', models.BooleanField(default=False)),
                ('right', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='triggers.TriggerChainItem')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triggers.Trigger')),
            ],
        ),
    ]
