# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 22, 23, 28, 332396, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='trigger',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Started'), (2, 'Paused'), (3, 'Stopped')], default=0),
        ),
        migrations.AddField(
            model_name='trigger',
            name='time_from',
            field=models.IntegerField(choices=[(1, 'From subscription')], default=1),
        ),
        migrations.AddField(
            model_name='trigger',
            name='title',
            field=models.CharField(default='test trigger', max_length=256),
            preserve_default=False,
        ),
    ]
