# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 23:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0002_auto_20171128_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerchainitem',
            name='start_after',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
