# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0003_auto_20171128_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='is_tg_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trigger',
            name='is_vk_connected',
            field=models.BooleanField(default=False),
        ),
    ]
