# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-28 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0006_auto_20171129_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triggerchainitem',
            old_name='start_after',
            new_name='_start_after',
        ),
    ]
