# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-05 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkconnector', '0010_auto_20171122_0141'),
        ('triggers', '0007_auto_20171129_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vkconnector.VKGroup'),
        ),
    ]
