# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0008_trigger_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='time_from',
            field=models.IntegerField(choices=[(1, 'From subscription'), (2, 'From mailing')], default=1),
        ),
    ]
