# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_umailing_title'),
        ('triggers', '0009_auto_20171210_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.UMailing'),
        ),
    ]
