# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models


def set_channel(apps, schema_editor):
    from common.models import SocialObject

    Trigger = apps.get_model('triggers', 'Trigger')

    for trigger in Trigger.objects.all():
        if trigger.is_vk_connected:
            trigger.channel = SocialObject.VK
        elif trigger.is_tg_connected:
            trigger.channel = SocialObject.TG
        trigger.save()


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0010_trigger_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='channel',
            field=models.IntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com'), (3, 'facebook.com')], null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='time_from',
            field=models.IntegerField(choices=[(1, 'Подписки'), (2, 'Рассылки')], default=1),
        ),
        migrations.RunPython(set_channel),
    ]
