# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0011_auto_20171210_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='is_tg_connected',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='is_vk_connected',
        ),
        migrations.AlterField(
            model_name='trigger',
            name='channel',
            field=models.IntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com')], null=True),
        ),
    ]
