# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0012_auto_20171210_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trigger',
            options={'ordering': ('-id',)},
        ),
    ]
