# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20171104_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_level',
            field=models.CharField(choices=[(0, 'No notification'), (1, 'Debug'), (2, 'Info'), (3, 'Warning'), (4, 'Error'), (5, 'Critical')], default=2, max_length=25),
        ),
    ]
