# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_profile_notification_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='tg_last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tg_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tg_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tg_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
