# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20171112_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
