# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkconnector', '0005_auto_20171105_2107'),
        ('tgconnector', '0001_initial'),
        ('common', '0006_profile_tg_phone_code_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='UMailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_mailing', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tgconnector.TGMailing')),
                ('vk_mailing', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vkconnector.VKMailing')),
            ],
        ),
    ]
