# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_umailing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='umailing',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
