# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20171122_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='umailing',
            name='content_validated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
