# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_umailing_content_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='umailing',
            name='title',
            field=models.CharField(default='Untitled mailing', max_length=256),
        ),
    ]
