# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0011_auto_20171122_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.TextField()),
                ('identifier', models.TextField(blank=True, null=True, unique=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.UMailing')),
            ],
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Link')),
            ],
        ),
    ]
