# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-23 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0003_auto_20171123_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkclick',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='countryCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='regionName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='zip',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkclick',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 12, 45, 11, 766693, tzinfo=utc)),
        ),
    ]
