# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-23 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0004_auto_20171123_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkclick',
            name='http_ua',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='linkclick',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 13, 45, 15, 55372, tzinfo=utc)),
        ),
    ]
