# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0008_auto_20171128_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkclick',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 22, 23, 28, 327391, tzinfo=utc)),
        ),
    ]
