# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-03 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.PositiveIntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com'), (3, 'facebook.com')])),
                ('created', models.DateTimeField(auto_now=True)),
                ('sid', models.PositiveIntegerField()),
                ('title', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('last_import', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VKMailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.PositiveIntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com'), (3, 'facebook.com')])),
                ('created', models.DateTimeField(auto_now=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VKMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.PositiveIntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com'), (3, 'facebook.com')])),
                ('created', models.DateTimeField(auto_now=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vkconnector.VKMailing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.PositiveIntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com'), (3, 'facebook.com')])),
                ('created', models.DateTimeField(auto_now=True)),
                ('sid', models.PositiveIntegerField()),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('isAllowedMessages', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vkconnector.VKGroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vkmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkconnector.VKUser'),
        ),
        migrations.AddField(
            model_name='vkmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
