# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkconnector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Unsubscribed'), (-1, 'Inactive')], default=-1),
        ),
    ]
