# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vkconnector', '0002_vkuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.PositiveIntegerField(choices=[(1, 'vk.com'), (2, 'telegram.com'), (3, 'facebook.com')])),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vkmailing',
            name='content',
            field=models.TextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='vksegment',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkconnector.VKMailing'),
        ),
        migrations.AddField(
            model_name='vksegment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vksegment',
            name='users',
            field=models.ManyToManyField(to='vkconnector.VKUser'),
        ),
    ]
