# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkconnector', '0003_auto_20171105_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkmailing',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vkconnector.VKGroup'),
            preserve_default=False,
        ),
    ]
