# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkconnector', '0004_vkmailing_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vkmailing',
            options={'ordering': ('-sent',)},
        ),
        migrations.AddField(
            model_name='vkmailing',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Failed'), (0, 'Draft'), (5, 'In progress'), (8, 'Partially completed'), (10, 'Completed')], default=0),
        ),
    ]
