# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkconnector', '0005_auto_20171105_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkmessage',
            name='sid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
