# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkconnector', '0012_vksegment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vksegment',
            name='mailing',
        ),
        migrations.AddField(
            model_name='vkmailing',
            name='segment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vkconnector.VKSegment'),
            preserve_default=False,
        ),
    ]
