# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('level', models.CharField(choices=[(0, 'No notification'), (1, 'Debug'), (2, 'Info'), (3, 'Warning'), (4, 'Error'), (5, 'Critical')], default=2, max_length=25)),
                ('created', models.DateTimeField(auto_now=True)),
                ('css_class', models.CharField(choices=[('fa fa-users text-aqua', 'fa fa-users text-aqua'), ('fa fa-users text-red', 'fa fa-users text-red'), ('fa fa-shopping-cart text-green', 'fa fa-shopping-cart text-green'), ('fa fa-warning text-yellow', 'fa fa-warning text-yellow')], default='fa fa-warning text-yellow', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ('-created',),
            },
        ),
    ]
