# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webnotification',
            name='css_class',
            field=models.CharField(choices=[('fa fa-users text-aqua', 'fa fa-users text-aqua'), ('fa fa-users text-red', 'fa fa-users text-red'), ('fa fa-shopping-cart text-green', 'fa fa-shopping-cart text-green'), ('fa fa-warning text-yellow', 'fa fa-warning text-yellow'), ('fa fa-user text-red', 'fa fa-user text-red')], default='fa fa-warning text-yellow', max_length=128),
        ),
    ]
